# Site settings
title: Spirits gonna wind up
email: betory9178@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple blog.By Neocosm Liang
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: betory
github_username:  betory9178

# Build settings
markdown: kramdown
